export const KEY_USER_AUTHSETTINGS = "USER_AUTHSETTINGS";
export const KEY_LISTUSERROLES = "USER_ROLES"
export const KEY_USER_LASTLOGIN = "USER_LASTLOGIN";
export const KEY_DEVICE_PUSHNOTIFICATION_TOKEN = "DEVICE_PUSHNOTIFICATION_TOKEN";
export const KEY_PUSHNOTIFICATION_REGISTERED_STATUS = "PUSHNOTIFICATION_REGISTERED_STATUS";
